### ISSUE TITLE
Fastmer.py error

### ISSUE THREAD

**Issue by Ashma45** [jts/assembly_accuracy#1]
Hi, 
I am using assembly_accuracy first time. I am getting the following error. Can you help me fix the issue?

Thank you

```
(base) [achakraw@vacc-user1 assembly_accuracy]$ ~/WGS/test/raw_reads/prokka_reads/assembly_accuracy/fastmer.py --reference GCF_000013425.1_ASM1342v1_genomic.fna --assembly 105_r2_prokka/*fsa --min-mapping-quality 10
```
Traceback (most recent call last):
  File "/users/a/c/achakraw/WGS/test/raw_reads/prokka_reads/assembly_accuracy/fastmer.py", line 304, in <module>
    subprocess.check_call(mm2_cmd, stdout=devnull, stderr=devnull, shell=True)
  File "/users/a/c/achakraw/miniconda3/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'minimap2 -Y -a -x asm5 GCF_000013425.1_ASM1342v1_genomic.fna 105_r2_prokka/*fsa | samtools sort -T 105_r2_prokka/*fsa.assembly_analysis.sorted.bam.tmp -o 105_r2_prokka/*fsa.assembly_analysis.sorted.bam -' returned non-zero exit status 127.

**Comment by jts** [comment]
Hi,

This repository is largely unmaintained so I apologize for the poor documentation and lack of error handling.

This error is likely because minimap2 is not found on your PATH.

Jared

**Comment by Ashma45** [comment]
Thank you, Jared!

I too doubted that minimap2 was not present on my PATH. But it is present when I check using ```minimap -h```
I see the documentation mentions ```pyvcf``` and ```pysam```. I installed both using conda but when I call ```pyvcf -h``` it returns as command not found.

**Comment by jts** [comment]
Is `samtools` available on your PATH as well?

**Comment by Ashma45** [comment]
Yes, the samtools is available on PATH. This time the error is as following

Traceback (most recent call last):
  File "./fastmer.py", line 6, in <module>
    import vcf
ModuleNotFoundError: No module named 'vcf'

**Comment by jts** [comment]
Both of those are python packages - can you try to install them using pip?

Jared
